### ISSUE TITLE
bug: failing test tests/integration/remote/test_e2e_docarray.py::test_end_to_end

### ISSUE THREAD

**Issue by Tanguyabel** [jina-ai/now#1016]
This test randomly fails on our CI, it seems flaky, see error:
```
FAILED tests/integration/remote/test_e2e_docarray.py::test_end_to_end[text-index_fields4-filter_fields4-model_selection4-team-now/best-artworks] - requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/search-app/search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f19f1692450>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

See https://github.com/jina-ai/now/actions/runs/4076391146/jobs/7024077393

**Comment by joschkabraun** [comment]
Thinking about it, it might not be worth it to investigate this test as the nature of this test (& post request) will change once [custom gateway](https://github.com/jina-ai/now/pull/921) is merged.

**Comment by joschkabraun** [comment]
[Custom gateway](https://github.com/jina-ai/now/pull/921) got merged.
