### ISSUE TITLE
feat: login to frontend

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#105]
Once someone wants to share a search case with clients, they have to deploy it on a cluster with public access. In case of private data, this is not what you would like to have. Instead, it should be possible to secure the service optionally.

- [x] create a login button on the playground. The button makes a python get request to the following link: https://api.hubble.jina.ai/v2/rpc/user.identity.authorize?provider=jina-login&response_mode=query&redirect_uri=https://nowrun.jina.ai/
- [x] forward the user to the link you got from the previous request.
- [x] check for the query parameters if it contains `code` and `state`
- [x] get the jwt by making a python get request to  https://api.hubble.jina.ai/v2/rpc/user.identity.grant.auto?code={code}&state={state}
- [x] when sending requests to the bff, you must include the jwt
- [x] the bff forwards the jwt to the flow gateway and pass it as request parameter
- [ ] the security executor validates the jwt using the hubbleSDK
- [ ] the security executor checks if the email is part of it's own set of allowed emails.
- [ ] everything only works if hubble includes email into the jwt. @delgermurun is working on this.
- [x] when making deployments with now ask for list of users to access
- [ ] make sure the 3 things are given to let the user pass through the executor
- email is in the list of allowed email addresses
- email matches the one from the token
- email is verified
- [ ] avatar shown in top right
- [ ] idea for the logout: clicking on avatar gives a drop down  to log out. But implementation can also be different if it is easier

**Comment by fogx** [comment]
Is it possible to do access control via Hubble? Via a hubble "project" or something?

**Comment by makram93** [comment]
Security Executor PR is ready: [#PR 80](https://github.com/jina-ai/now.private/pull/80)

**Comment by delgermurun** [comment]
@florian-hoenicke try adding `scope=email%20profile%20openid` query param to `/user.identity.authorize` request.
With this I can see that `email` is included in the response of `..c/user.identity.grant.auto?..` request.

here is the full link:
https://api.hubble.jina.ai/v2/rpc/user.identity.authorize?provider=jina-login&response_mode=query&redirect_uri=https://nowrun.jina.ai/&scope=email%20profile%20openid

**Comment by makram93** [comment]
> Once someone wants to share a search case with clients, they have to deploy it on a cluster with public access. In case of private data, this is not what you would like to have. Instead, it should be possible to secure the service optionally.
> 
> * [ ]  create a login button on the playground. The button makes a python get request to the following link: https://api.hubble.jina.ai/v2/rpc/user.identity.authorize?provider=jina-login&response_mode=query&redirect_uri=https://nowrun.jina.ai/
> * [ ]  forward the user to the link you got from the previous request.
> * [ ]  check for the query parameters if it contains `code` and `state`
> * [ ]  get the jwt by making a python get request to  [https://api.hubble.jina.ai/v2/rpc/user.identity.grant.auto?code={code}&state={state}](https://api.hubble.jina.ai/v2/rpc/user.identity.grant.auto?code=%7Bcode%7D&state=%7Bstate%7D)
> * [ ]  when sending requests to the bff, you must include the jwt
> * [ ]  the bff forwards the jwt to the flow gateway and pass it as request parameter
> * [ ]  the security executor validates the jwt using the hubbleSDK
> * [ ]  the security executor checks if the email is part of it's own set of allowed emails.
> * [ ]  everything only works if hubble includes email into the jwt. @delgermurun is working on this.
> * [ ]  when making deployments with now ask for list of users to access

Thanks for creating the list. While working on this, I found a lot of shortcomings in streamlit. Below are the observations:
- Button with hyperlink (directing to some URL) is not possible. The alternative is to have text with hyperlinks in a markdown style. E.g, Please [login](google.com)
- No pop-up support. So, the alternative is to hide the search bar and ask for login and only when logged in, allow the search bar to show
- Session state cannot be used to store the jwt value, as the session state is erased whenever the page is [refreshed or a new tab is opened](https://discuss.streamlit.io/t/allow-access-to-sessionstorage-and-localstorage/25257). Cannot use sessionStorage or localStorage as it is not currently supported in streamlit. Alternative - To make use of cookies to store the data. It is not very stable but can solve our task(hopefully).  Also, a cookie only stores string value, so we have to convert to jwt dict to str and then convert back to dict at the executor level. Proble with this approach is that user who would like to use BFF/Client also has to get jwt and process it accordingly. So, we will have to write up a doc page to inform how to pass. If you have any better suggestion, then it would be nice to hear
- Our playground URL has query param(like host, input modality, etc.) So, when we make a request to the below URL:
`https://api.hubble.jina.ai/v2/rpc/user.identity.authorize?provider=jina-login&response_mode=query&redirect_uri=https://nowrun.jina.ai/?host=grpcs://nowapi-613a147629.wolf.jina.ai&input_modality=image&output_modality=image&data=custom`
The return link with code is something like this:
`https://nowrun.jina.ai/?host=grpcs%3A%2F%2Fnowapi-613a147629.wolf.jina.ai&code=kqR0cs7Wzu4nQAnadaOjE0tBoU6IewdtKlilVf6hpsMSd&state=jina-login%3A2d519d4ec9e6bc9ed7cb7c96fb7a976d`, thereby omitting our query param and also changing the host URL. Either we write a workaround for this or we raise this hubble team and ask them to not modify the redirect URL.
@florian-hoenicke

**Comment by florian-hoenicke** [comment]
@delgermurun As you suggested me, I tried as well with google and github. In both cases, I get the e-mail. Thanks for finding this out!
