### ISSUE TITLE
bug: playground search on enter not working

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#1059]
When hitting enter, the search is not working in the playground

![Image](https://user-images.githubusercontent.com/11627845/218113763-9463d485-6889-46ba-926e-da5f45670e56.png)

**Comment by IyadhKhalfallah** [comment]
@florian-hoenicke I couldn't reproduce this. Does this still happen?

I tried with customer data and hit ENTER on every input I add, it seems to output results as expected
