### ISSUE TITLE
feat: go back to previous menu

### ISSUE THREAD

**Issue by CatStark** [jina-ai/now#11]
**User story**: As an user I would like to be able to go back to previous menus on the terminal. So that I could see what are all the possible options and go back to any once I decided what option I want. 

**Example:**
Once I'm in this option, I would like to go back to use the example data instead of pushing my own DA
<img width="566" alt="Screenshot 2022-03-21 at 13 49 26" src="https://user-images.githubusercontent.com/3002344/159269726-be4b7918-56d7-478f-a5fb-229c2dcb9a09.png">

**Comment by makram93** [comment]
As discussed, this ticket won't be handled. We are moving towards having a storefront app and hence this feature request will not be relevant anymore.
