### ISSUE TITLE
🚨 ci: investigate idle CI runs

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/now#1109]
Find out why there are often idle CI flows and fix their removal.

Hint:
- maybe we can name the flows by the current branch & first few letters of SHA, to link flows with PR
- for most cases the runner times out before the test. Therefore the cleanup fixture can not be called. Solution: timeout the test before the runner times out

**Comment by florian-hoenicke** [comment]
Example

![Image](https://user-images.githubusercontent.com/11627845/221232267-41bcb718-3564-4849-9ed6-caae7d2e05f6.png)

**Comment by florian-hoenicke** [comment]
We need to let the test time out before the runner times out

**Comment by joschkabraun** [comment]
Other potential issue: if wolf deployment reaches phases `Updating` instead of `Started`, then this won't be caught by our cleanup function and the flow still exists on the cluster.

Looking at output of `pytest` to extract the flow ID, can help removing the flow.
