### ISSUE TITLE
refactor: add logs all over the code base

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#1117]
- [x] add logs in the auth executor to make sure all executors inherit the logging behaviour
- [x] log first document of input and first document of output for each endpoint
- [x] log parameters
- [x] log docs, docs_matrix, docs_map
- [ ] log bff
- [ ] truncate blobs to not pollute the logs (maybe solved already by d.summary())
- [x] use jina logging module
- [x] make sure logging can easily be turned on/off (optional: different log levels)
- [ ] (maybe new ticket) stream logs of all executors when running `now start...` (grafana or streaming directly from the cluster)

**Comment by Tanguyabel** [comment]
Check if https://github.com/jina-ai/jina/pull/5736 would bring any relevant change.

**Comment by girishc13** [comment]
I'm proposing to mainly remove the suppression of root logging which prevents logging from the underlying dependencies. This is a very bad practice as it gives an impression that the jina or now code is at fault and prevents debugging underlying issues. We should rely on logs to expose the error to the user.

**Comment by girishc13** [comment]
I also suggest using module level or package level logging for tracing or debugging certain parts of the code. This logging needs to be enabled specifically in code or using custom environment variables. These loggers can be set at DEBUG level by default or even completely turned off by default using

```python
connection_pool_logger = logging.getLogger('connection_pool_logger')
connection_pool_logger.setLevel(logging.DEBUG)
connection_pool_logger.addHandler(logging.NullHandler)
```

If needed the user needs to do the following:
```python
logging.getLogger('connection_pool_logger').addHandler(sys.stdout)
```

**Comment by Tanguyabel** [comment]
Thanks @girishc13 for the input, this all makes sense. I initially thought of using the wrapper JinaLogger:

```
os.environ['JINA_LOG_LEVEL'] = os.environ.get('JINA_LOG_LEVEL', 'INFO')
app_logger = JinaLogger("app")
```

Would you go this way?

**Comment by girishc13** [comment]
The current version remove root level logging by default which means that you cannot enable DEBUG logging of other libraries or dependencies. You can only see the logs from the JinaLogger. I'm [removing](https://github.com/jina-ai/jina/pull/5736) this behavior so if you plan to upgrade to the latest jina version then you can continue using the JinaLogger.

**Comment by Tanguyabel** [comment]
Ok so at the moment we will stick to JinaLogger for logging from our modules, and keep in mind that if we need to enable logging for other libraries, we should do so separately using dedicated loggers.

Another point: when we add more loggings to ease troubleshooting of modules, we might run into disk capacity issues for our executors. Ideas to tackle this would be:
- trim the logs on local volumes and rely on loki for long-term logging
- use not only a single log level per deployment, but allow to override the log level on a per-module basis; like this we could enable full debug logging only for the chosen module and allow reduce logs pollutions from other modules

**Comment by Tanguyabel** [comment]
I created two follow-up tickets for tasks that fall out of the scope of this ticket: https://github.com/jina-ai/now/issues/1203 and https://github.com/jina-ai/now/issues/1204
