### ISSUE TITLE
update jina-now 

### ISSUE THREAD

**Issue by mashuaitop** [jina-ai/now#132]
The original version of my jina is 0.0.3.dev64, I want to upgrade to the latest version 0.0.3.dev84, but I cannot upgrade directly using pip install jina-now, I have to delete the original version and reinstall jina-now Yes, it's not very convenient

**Comment by makram93** [comment]
Hi @mashuaitop 
Did you try `pip install -U jina-now`? I am unable to reproduce this. I installed `pip install jina-now==0.0.3.dev64` and then ran `pip install -U jina-now` and was successfully able to upgrade

<img width="888" alt="image" src="https://user-images.githubusercontent.com/6537525/165899157-e40074b2-2726-4c5d-9645-0acc5f337c0d.png">

Let us know if this still persists. Thank you for trying out Jina NOW :)

**Comment by florian-hoenicke** [comment]
I hope the response from @makram93 helped you
