### ISSUE TITLE
路径搜索失败

### ISSUE THREAD

**Issue by tswysy** [jina-ai/now#135]
我用的mac系统，选择自定义数据路径的时候，我直接把文件夹拖入到控制台中，索引图片没有显示任何进度，服务启动成功但是搜不到图片

On macOS, when I customize the data path, I simply dragged a folder into the terminal, It didn't show any progress during indexing. The service was started but no images could be searched.

**Comment by makram93** [comment]
Hi @tswysy,

Thank you for trying out Jina NOW.

Can you try again with the lates version of `jina-now` and share the screenshot? `pip install -U jina-now`. Can you also let us know following details, which will help us to better understand the problem and reproduce it:
- OS
- Architecture
- M1 or Intel if macbook
- Conda or virtualenv
- Python version

**Comment by nomagick** [comment]
拖进来的话好像会多一个空格，删掉最后一个空格试试

**Comment by nomagick** [comment]
> On macOS, when I customize the data path, I simply dragged a folder into the terminal, It didn't show any progress during indexing. The service was started but no images could be searched.

It could be the extra space from dragging causing some malfunction, could you try removing the trailing space?

**Comment by florian-hoenicke** [comment]
@tswysy thanks again. I will close this issue. In case your problem is still not solved, we can reopen it.
