### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by nawabhussain** [jina-ai/now#141]
Pip installation fails on Windows with the error message: `RuntimeError: uvloop does not support Windows at the moment`

In order to get around the above error, I used the WSL python environment to get jina-now up and running. It would be nice to have it added to the documentation.

**Comment by florian-hoenicke** [comment]
Hi @nawabhussain, thanks a lot for raising the issue.
Currently, we don't support windows. I will make this clear in the readme. Thanks

**Comment by florian-hoenicke** [comment]
fyi: https://github.com/jina-ai/now/commit/95e1f447dfe5357f3f665c8b28fc95b6b3650f82

**Comment by nawabhussain** [comment]
@florian-hoenicke Perhaps it would also be a good idea to mention the WSL (Windows Subsystem for Linux) as a workaround for Windows?
