### ISSUE TITLE
fix: remove upgrade jina version info

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#142]
remove warning. 
You can use the environment variable`JINA_CHECK_VERSION=False`
```
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/cli/__init__.py:123: UserWarning: You are using jina version 3.3.14, however version 3.3.22 is available. You should consider upgrading via the "pip install --upgrade jina" command.
  f'You are using {package} version {cur_ver}, however version {latest_release_ver} is available. '
```

**Comment by makram93** [comment]
This has to be added to our docs and mentioned as a note that it should be added to the environment by the user himself. We can add this variable to env in our code however if a user runs NOW via Jina - `jina now start` then the first control will be with Jina, which will perform a check and log warning, and then the control will come to NOW, which will set the variable and thereon we will not get warnings.

We can add to code and make sure that when the user runs `jina-now start` they won't see such warnings. But if they start via  `jina now start` then this env variable has to be added by the user.
