### ISSUE TITLE
feat: add text-to-[image+text]

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#155]
- create draft 
- propose approach 
- implement app

Hint: maybe the executor created by @jemmyshin will be useful

**Comment by joschkabraun** [comment]
@jemmyshin is working on an executor which will be useful for us. He will open a PR for it next week. I will follow-up & pair with him then.

**Comment by joschkabraun** [comment]
Current idea: Combine BM25 scores with scores from CLIP for text and image. Depending on latency of search requests investigate option to first filter by BM25 and then rerank with CLIP scores. This might depend on dataset size.

Initial experiments gave that fine-tuning of CLIP is required to yield good results.

**Comment by florian-hoenicke** [comment]
Will be continued in this ticket https://github.com/jina-ai/now/issues/382
