### ISSUE TITLE
Show resource in a tabular format

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#18]
When running `jina -h` in terminal we something like this at the bottom: 

<img width="691" alt="image" src="https://user-images.githubusercontent.com/6537525/159449540-15afbd1e-1674-43a2-a572-8e8ca4d8258e.png">

Similarly, when a user runs `jina-now -h` after installing the pip package, they should see the resource links in a tabular format. However, currently it is not displayed in that format:
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/6537525/159449775-21b1a3d1-9270-4b0d-97c8-4ae17eaf221c.png">

**Comment by florian-hoenicke** [comment]
done
