### ISSUE TITLE
feat: wolf deployment using token directly

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#192]
Please add the token parameter to the now package. It should be possible to call the now package using a given token

You can assume the token is already there using the method described here:
https://github.com/jina-ai/hubble/blob/master/docs/user-api.md

**Comment by makram93** [comment]
After discussing with @deepankarm about this requirement the conclusion is that this feature is currently not supported by JCloud and would be worked on in the new version. I have created [a ticket](https://github.com/jina-ai/wolf/issues/152) on the `wolf` repo for this feature to be added in JCloud and only then we can proceed with the required changes in our codebase.

**Comment by florian-hoenicke** [comment]
done
