### ISSUE TITLE
refactor: survey

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#199]
- free form responses
- more modality
- multi select
- enter contact information

**Comment by fogx** [comment]
closed by https://github.com/jina-ai/now/pull/216/commits

**Comment by fogx** [comment]
try it out: https://10sw1tcpld4.typeform.com/to/VTAyYRpR?utm_source=test

**Comment by joschkabraun** [comment]
I really like the survey! A little bit of feedback:

- point 4: option E isn't capitalised
- point 5: option D isn't capitalised
- point 6: I would have the option of only doing a project w/o being a company
- point 8: typo, it's Jina NOW

**Comment by fogx** [comment]
@joschkabraun thanks for the feedback, i have modified the survey accordingly.
