### ISSUE TITLE
feat: integrate with finetuner.fit

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#213]
At the moment, we use the community version of finetuner. However, the finetuner.fit api is ready to be used.
Migrating gives us the following benefits:
- we won't need the local dependencies like PyTorch anymore since the finetuner client is lean.
- we dogfeed our own service
- finetuner.fit comes with improvements of the training and new futures like training with multiple modalities.

**Comment by slettner** [comment]
The finetune api needs the following enhancements before we can move further:
- expose callbacks `EvaluationCallback` and `EarlyStopping` via configurations
- implements `LinearHead` model 

We can expect those updates end of next week (ticket is blocked until then)

**Comment by florian-hoenicke** [comment]
Great finding. 
@gmastrapas do you have a rough time estimate for these things?

**Comment by gmastrapas** [comment]
We will try having these end next week

**Comment by fogx** [comment]
blocked because the executor is not loading - dependent on a Jina/hubble bug
