### ISSUE TITLE
docs: add section for bff swagger 

### ISSUE THREAD

**Issue by slettner** [jina-ai/now#218]
Add a section to the documentation pointing out the use of the swagger docs for sending http requests similar to here:
https://docs.jina.ai/fundamentals/flow/access-flow-api/?highlight=swagger#use-swagger-ui-to-send-http-request

Maybe we can also print a reference to the docs at the end of the jina now command. Like "not sure how to interact with the flow? Check out our docs to learn more! "

**Comment by florian-hoenicke** [comment]
good idea. For now we close it due to other high priority tasks.
