### ISSUE TITLE
feat: make use of external executor

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#236]
Currently, our flow for the available apps consists of `CLIPEncoder` executor. Every time we run `jina now` this flow is deployed. Taking inspiration from the docsqa team, we can reuse our `CLIPEncoder` executor as it is stateless. This ticket is for investigating how the concept of external executor can be applied to our Jina NOW app and also work for its implementation. Although our flow is very short, yet it can help us speed up even more, and also this will be helpful when we have more apps added with the complex flow in the future.

The developer can refer to this [PR](https://github.com/jina-ai/docsQA/pull/653) to see how it is implemented currently in the DocsQA

**Comment by makram93** [comment]
While discussing with @florian-hoenicke, we realized that using external executors does not add much value to our use case while requiring considerable changes in the codebase. Therefore we are inclined towards using `sandbox` with `JCloud`. You can follow [this thread](https://jinaai.slack.com/archives/C023A7RAPGR/p1654695905300109) for the general opinion about merging sandbox features with JCloud features which will not happen anytime soon. 

---

[Update]: Upon investigating the performance of using `+sandbox` with the `JCloud`, I found that the `+docker` version is more faster. Below is the attached screenshot for the deployment with `+sandbox`. There are three images and all were run consecutively one after another. Our belief is that the first execution with sandbox could take time, however, the subsequent executions should take less time but as we observe from the screenshot there's no difference. 

<img src="https://user-images.githubusercontent.com/6537525/173060792-95538cb5-c3c0-453f-b022-861316807a82.png" width="200"> <img src="https://user-images.githubusercontent.com/6537525/173060812-30579a18-263e-4785-96b3-a577d3e1a5e7.png" width="200"> <img src="https://user-images.githubusercontent.com/6537525/173060831-075503d7-a046-438e-a0b6-57d5b61175e4.png" width="200">

When comparing this with the `+docker` deployment, we find that the docker version of the CLIP executor takes less time to execute, as shown in the below screenshot. 

<img src="https://user-images.githubusercontent.com/6537525/173062260-588b7e81-cced-41b5-9104-e859a4e16cab.png" width="200"> <img src="https://user-images.githubusercontent.com/6537525/173062275-ef8cd3ac-185f-45ce-941d-ba70552a9722.png" width="200">


Hence, I would recommend we keep the `+docker` version as of now and migrate to `+sandbox` when the sandbox and JCloud feature is merged or when we see that adding an external executor adds more value then we can work towards integrating it.

@florian-hoenicke @joschkabraun @slettner  - Any feedbacks or comments are much appreciated

**Comment by florian-hoenicke** [comment]
That makes sense. We migrate once it is stable. Thanks for the deep investigation
