### ISSUE TITLE
Feat: Add new Indexer

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#239]
When running the Flow on JCloud we should have an indexer which stores the data on a disk or some database instead of memory. The argument in favor of this is that after the flow is deployed and the data is indexed. If for any reason the indexer pod is restarted then all the indexed data will be wiped out forcing us to reindex, however, if we have it persisted on a volume of in some database then the indexed data will not be lost.

**Comment by florian-hoenicke** [comment]
Done by @joschkabraun - sqlite indexer
