### ISSUE TITLE
fix: replace indexing progress bar

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#255]
Please follow [this slack thread](https://jinaai.slack.com/archives/C01E03LN3K7/p1654766880489849) to understand the problem better. To summarize in short:
When JCloud is used for deployment we observe the following problems/drawbacks with it:
- The flow is started by JCloud, however the indexing does not start and gets stuck in [the infinite loop](https://jinaai.slack.com/archives/C01E03LN3K7/p1654766880489849) because the dummy response sent to JCloud fails. This does not mean that the flow deployed by the JCloud is wrong or not working. It is working and to verify, once the flow is started by JCLoud you can start a python execution in another terminal and make a request via Jina Client and it will be successful. This problem is speculated to be due to a DNS propagation error and it is currently being solved by the 🐺 team. The ticket to track is [here](https://github.com/jina-ai/wolf/issues/147)
- The second problem that we noticed is that after the indexing is done the program freezes out (or gets stuck) and there's no response from the program. It eventually proceeds but after quite some time which might give the feeling to the user that it is not working as expected and may terminate the program early. As suggested by @florian-hoenicke, it might be due to prefetching. The progress bar shown during indexing depends on the number of docs sent to the gateway however it may be that these requests are just queued up at the gateway and waiting to be processed meanwhile our progress bar assume it is done and hence the indicator progresses fast to 100%. Even though the progress bar says it is done, behind the scene, it is still being processed by the gateway, this causes the program to feel `stuck` and wait until all docs processing are done to resume Jina NOW! One approach to solving this would be to replace our progress bar and make it slide only when a successful response is received from the gateway, that way the progress bar will show actual indexing progress.

**Comment by florian-hoenicke** [comment]
@makram93 Thanks for creating the ticket. Is this still up to date? Or is the issue resolved?
