### ISSUE TITLE
fix: music to music app times out for the default dataset

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#295]
![Image](https://user-images.githubusercontent.com/6537525/177109135-2de3a044-a031-4704-83d0-ab1ea76cf96e.png)

![Image](https://user-images.githubusercontent.com/6537525/177109174-ba9a5e2e-dfd9-4850-a8f3-05a372727e23.png)

**Comment by fogx** [comment]
maybe its possible to include a different compression type to shrink the files?

**Comment by florian-hoenicke** [comment]
By now the deployment is working. So I will close this ticket
