### ISSUE TITLE
docs: update to make it easier understandable

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/now#303]
- [ ] add finetuning to the docs
- [ ] bff description
- [ ] production readiness (QPS 13, latency 300 ms)    
- [ ] security
- [ ] s3 bucket
- [ ] also add google analytics
- [ ] find out more things to add

**Comment by joschkabraun** [comment]
https://jina-ai.slack.com/archives/C0169V26ATY/p1657616879044809?thread_ts=1657574281.102059&cid=C0169V26ATY

**Comment by azayz** [comment]
![Screenshot from 2022-09-19 11-34-29](https://user-images.githubusercontent.com/40893766/191000917-88a903ec-bf0d-4206-9e9b-029401c34843.png)

**Comment by azayz** [comment]
![Screenshot from 2022-09-19 11-53-02](https://user-images.githubusercontent.com/40893766/191002151-4cb2d223-a266-45ea-87cd-57c4968059de.png)

**Comment by azayz** [comment]
![Screenshot from 2022-09-19 11-54-31](https://user-images.githubusercontent.com/40893766/191002373-b660df33-0f36-44d4-9f81-3e8ad8e026ab.png)

![Screenshot from 2022-09-19 11-56-19](https://user-images.githubusercontent.com/40893766/191002764-049037fb-6eb7-44a6-8b22-c86687b95e0f.png)

**Comment by azayz** [comment]
update API key use this script https://github.com/jina-ai/now/blob/main/now/admin/update_api_keys.py

**Comment by azayz** [comment]
![Screenshot from 2022-09-20 09-25-42](https://user-images.githubusercontent.com/40893766/191207810-e1a1df17-acf3-4de2-8211-9a297b52e3a8.png)

**Comment by azayz** [comment]
![test](https://user-images.githubusercontent.com/40893766/191584585-93b8b24f-4e90-4a61-aabf-c4eb57985d58.gif)

**Comment by azayz** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/40893766/191586156-d9e4839b-8cc6-4f68-8c13-b4e9352de21d.gif)

**Comment by azayz** [comment]
![pic2](https://user-images.githubusercontent.com/40893766/192243437-9fd6c852-d1b1-4ed1-8ac8-ed7b3c02527f.png)

**Comment by azayz** [comment]
![pic3](https://user-images.githubusercontent.com/40893766/192243720-a4881579-7346-4fe0-b41b-b1877eeec103.png)

**Comment by azayz** [comment]
![pic4](https://user-images.githubusercontent.com/40893766/192243962-6cf9c1d1-deb8-4f06-a65e-47271a472d92.png)

**Comment by azayz** [comment]
![prompt1](https://user-images.githubusercontent.com/40893766/192245825-c19274a5-2514-4c93-94ff-4d507dfef429.png)

**Comment by azayz** [comment]
![prompt2](https://user-images.githubusercontent.com/40893766/192245979-66376fc2-2629-4932-a747-b3f526bfd53a.png)
