### ISSUE TITLE
feat: make playground login look more professional

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#352]
It is great that we can login into the playground.
In the next iteration, let's focus on making the login experience better by having a more professional looking button

This is how it looks right now:
![Image](https://user-images.githubusercontent.com/11627845/184920940-b8391016-fcb0-4cae-8a18-45fefdc4ea68.png)

Suggestions to beauty it up:
- use Jina NOW color scheme
- center button
- button design in typical streamlit design

**Comment by florian-hoenicke** [comment]
as discussed in the refinement, @fogx will ask the design team  for input

**Comment by fogx** [comment]
can't we just redirect to the login page directly, instead of showing this intermediate page? Then we don't need any design at all.

**Comment by florian-hoenicke** [comment]
You are awesome. Yes, we can
