### ISSUE TITLE
feat: add video example dataset & test

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#359]
@joschkabraun and @fogx were using a gif example dataset in the past.
Next step would be to add it to our example datasets to allow easy deployment of a showcase

Hint:
- link to dataset: https://github.com/raingo/TGIF-Release

UAC:
- [ ] example dataset is available
- [ ] deploy public example case

**Comment by joschkabraun** [comment]
This example dataset should be also used to write a test for `text-to-video` search
