### ISSUE TITLE
refactor: implement custom gateway

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#366]
request docs page for grcp deployments on wolf

UAC 

- [ ] add BFF logic to app
- [ ] once the app is updated, a new gateway image has to be built
- [ ] implement our own custom gateway

**Comment by fogx** [comment]
custom gateway is released now from Core

**Comment by fogx** [comment]
custom gateway is released now from Core

**Comment by JoanFM** [comment]
Custom Gateway is hiddenly released from `Core` and will not be in the exact same shape, but u can internally start using it. Some minor changes may come in other versions.

You can consult @alaeddine-13 on how to do it

**Comment by florian-hoenicke** [comment]
We can not start with it at the moment because:
- Https endpoint enabled for bff / playground
