### ISSUE TITLE
fix: image-image webcam snapshot does not work

### ISSUE THREAD

**Issue by fogx** [jina-ai/now#375]
The snapshot button does nothing and the widget/preview is cut off wierdly?

![Image](https://user-images.githubusercontent.com/10303647/185611504-4d9ee2f8-f53f-4fab-966e-809d2a7adb19.png)

**Comment by fogx** [comment]
https://nowrun.jina.ai/?host=grpcs://nowapi-27da833691.wolf.jina.ai&input_modality=image&output_modality=image&data=tll

**Comment by makram93** [comment]
The image search is working. The problem might be from the JCloud side. Closing, this ticket @fogx  will create a follow-up ticket with low priority to change the behavior when the `stop` button on the webcam is clicked i.e., persisting the last search instead of clearing it
