### ISSUE TITLE
fix: music-to-music mp3 upload fails with 413 error

### ISSUE THREAD

**Issue by fogx** [jina-ai/now#377]
i downloaded an mp3 ([this one](https://www.singing-bell.com/mary-had-a-little-lamb/)) and tried uploading it to the [music search example](https://nowrun.jina.ai/?host=grpcs://nowapi-d8e6b2e36c.wolf.jina.ai&input_modality=music&output_modality=music&data=music-genres-mix)
but get the error message:
`Error: Request failed with status code 413`
It is not clear what the issue is and how i can fix it (or if it's my fault or a server side problem)
I assume 413 is a `request entity too large` error
> A 413 HTTP error code occurs when the size of a client's request exceeds the server's file size limit. 

But the hint says i can upload songs up to 200mb and my file is 3mb.

![Image](https://user-images.githubusercontent.com/10303647/185613857-5db39341-0be1-4531-93b1-c9fa7cdad1fc.png)

**Comment by florian-hoenicke** [comment]
@makram93 I assigned you because I think it would be easiest for you to fix and you already started the investigation if I'm not mistaken.
