### ISSUE TITLE
fix: webcam search bff

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#381]
As reported by @alexcg1 there is a problem with our webcam search.
https://nowrun.jina.ai/?host=grpcs://nowapi-27da833691.wolf.jina.ai&input_modality=image&output_modality=image&data=tll

![Image](https://user-images.githubusercontent.com/11627845/185807887-40e14d8e-0448-4693-8ba5-47d48faa5df9.png)

**Comment by florian-hoenicke** [comment]
I think for @makram93 it will be easy to fix

**Comment by makram93** [comment]
Solved in #387
