### ISSUE TITLE
FileNotFoundError in quick start if user haven't log in

### ISSUE THREAD

**Issue by pingren** [jina-ai/now#384]
I followed the docs https://now.jina.ai/#usage to run `jina now start` 
but encounter this exception:

```
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/now_common/utils.py", line 175, in _get_email
    with open(user('~/.jina/config.json')) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ping/.jina/config.json'
```

Suggestion to fix:
 1. Fix the documentation to inform users to run [`jc login`](https://docs.jina.ai/fundamentals/jcloud/#login) explicitly, if they haven't done it yet
 2. Alternatively, make this config optional until user choose to deploy to JINA Cloud

**Comment by joschkabraun** [comment]
Hi @pingren, thank you for raising this issue! We also noticed that problem and fixed it in the `main` branch. I just triggered a release of the next version such that you can upgrade the version.
