### ISSUE TITLE
fix: abort if docker runs out of disk space.

### ISSUE THREAD

**Issue by slettner** [jina-ai/now#42]
<img width="1768" alt="Screenshot 2022-03-25 at 12 02 17" src="https://user-images.githubusercontent.com/51201318/160112407-a72ca905-73bb-4256-a11e-ca1a91345a60.png">

Jina-Now should probably abort or handle this error in some way.
It can be solve by increasing the disk space resource in the docker settings.

**Comment by florian-hoenicke** [comment]
Thanks for reporting. You are right we have to address this error instead of just continuing
