### ISSUE TITLE
refactor: embed demo datasets

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/now#482]
In order to cost save & quickly show demos host (some) demo datasets permanently on a static URL in docs.

(we're doing this to have example deployments on the storefront)
UAC 

- [ ] embed demo datasets in a section in the docs

- [x] #556

  - when someone chooses demo data, then they will be pointed towards the static URL in the docs for that particular demo
- [x] #569
  - need to add to `flow-clip.yml`, `flow-sbert.yml` and any other relevant `flow.yaml` the following line under jcloud: `custom_dns: now-example-${{ ENV.APP }}-${{ ENV.DEMO_DATA }}.dev.jina.ai`
    - cf. more:
        
        [https://jinaai.slack.com/archives/C03434J5BND/p1662473489965669?thread_ts=1662119465.049149&cid=C03434J5BND](https://jinaai.slack.com/archives/C03434J5BND/p1662473489965669?thread_ts=1662119465.049149&cid=C03434J5BND)
  - also need to add `CNAME` record to Route53 for `dev.jina.ai`
 - [x] #570

**Comment by fogx** [comment]
how much does it cost to keep a flow alive for one week? and how much does it cost to deploy a new flow?
