### ISSUE TITLE
fix: docarray indexer persistent storage problem

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#485]
Docarray indexer does not have persistent storage. Means when the pod is killed, it does not contain the data anymore.
Three possible solutions:
- make it persistent by using a storage backend for docarray
- always use annlite indexer for remote deployment
- don't use docarray indexer anymore

As discussed in our planing meeting, we decided to go for the third option. Let's just delete the docarray indexer.

**Comment by joschkabraun** [comment]
Closed by https://github.com/jina-ai/now/pull/491
