### ISSUE TITLE
feat: add user-based auto-complete endpoint

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/now#503]
- [x] research auto completion libraries and choose the best one (importance to the fact the we can add our add vocabulary perhaps use tags) 
1. use preconfiguration
2. use index data
3. start from scratch use search data
- [x] implement executor // to all the other executors in the flow (add tests)
- [x] `/search` endpoint to update user queries with any search
- [x] `/get_suggestion` to get auto-completion suggestions for given query (use library for this)
- [x] add `get_suggestion` to bff for apps with input modality text
- [x] add end to end test
- [x] update playground 
- [x] add documentation about the feature

**Comment by makram93** [comment]
Waiting for the frontend team to implement the search bar template to be integrated in the playground
