### ISSUE TITLE
research: investigate cost of flow deployment

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/now#512]
- get cost per indexer to keep it alive (because that will be the only cost using serverless deployment)
- how much does it cost right now to host a flow
- serverless deployment is needed

UAC
- [ ] investigate cost of flow deployments
- [ ] choose which datasets to deploy

**Comment by azayz** [comment]
| Dataset   |      Weekly Costs      |
|----------|:-------------:|
| text to image best works |  $6.39 |
| text to image fashion |    $7.72   |
| image to text rap lyrics | $8.99 |
| image to image ttl | $9.13 |
| text to text rock | $12.27 |
