### ISSUE TITLE
feat: activate serverless

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/now#514]
We want to make other (stateless) executors serverless, like the preprocessor.

UAC
- [ ] remove all uses_with/ uses_metas parameters
- [ ] deploy stateless executor (ask wolf how to do it)
- [ ] measure how long it takes for the instance to run
- [ ] wake up time for each executor we have
- [ ] dependent on the outcome use stateless executors or not

**Comment by fogx** [comment]
@jupyterjazz can you clarify this ticket?
