### ISSUE TITLE
bug - style: make NOW URL more obvious

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/now#530]
It takes some looking to find the hosted NOW URL after everything is set up. It should be more prominent. The first thing I see if the "Flow is available!" box

![image](https://user-images.githubusercontent.com/4182659/191729706-a93eba47-b7b4-4cc7-8ba6-fed87e2ca787.png)

**Comment by fogx** [comment]
this seems like a feature request, not a bug fix

**Comment by florian-hoenicke** [comment]
We can remove the json in the last column.
We could color the text.
@alexcg1 Would this solve your problem?

**Comment by azayz** [comment]
![Screenshot from 2022-09-27 10-24-15](https://user-images.githubusercontent.com/40893766/192488431-10c33f0c-407d-424d-b879-62581de02787.png)

**Comment by alexcg1** [comment]
Nice
