### ISSUE TITLE
fix: correct byte unit in CLI interface (Low priority)

### ISSUE THREAD

**Issue by fogx** [jina-ai/now#565]
The loading bar shows (ex.) "100M / 140M". M is the unit for Million. The CI-unit for Megabyte is Mb (which i assume is the one we want to show)

![Image](https://user-images.githubusercontent.com/10303647/193997001-2a2ea509-d096-4ade-a98d-337d6a544579.png)

UAC:

- [ ] use correct unit to show status in the loading bar

**Comment by azayz** [comment]
https://tqdm.github.io/docs/tqdm/#__init__ 

We don't have control over this, this is specified by tqdm library, I tried playing with parameters, unit, unit scale but it's not possible to change M to Mb
