### ISSUE TITLE
refactor: remove postprocessor?

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#571]
Is there a reason to keep the post processor?

**Comment by florian-hoenicke** [comment]
What do you think @joschkabraun ?

**Comment by joschkabraun** [comment]
Yes, we need it e.g. to remove any loaded content attributes before putting them into the indexer. Except for we modify every indexer to not save these attributes.

**Comment by azayz** [comment]
closed https://github.com/jina-ai/now/pull/590
