### ISSUE TITLE
feat/refactor: create new playground

### ISSUE THREAD

**Issue by azayz** [jina-ai/now#625]
due to the limitations of streamlit: 
- inability to provide complex front end features such as full autocomplete, on key press callbacks and full control on provided elements. 
- complexity of integrating dynamic html (very hard to use bi directional components that can take python variables as inputs and return javascript variables)
- streamlit updates by reruning the whole script on every small change which is inefficient. 
- streamlit is designed to create a frontend for ml applications as fast as possible but at this point we are introducing more and more complex features that are outside of this scope. 

I propose we create new frontend that doesn't use streamlit at all and is based on another frontend framework. This will allow more maintainability and ease of introducing new featues.

**Comment by fogx** [comment]
[related ticket on Cloud Apps side](https://github.com/jina-ai/hub-website/issues/226)

**Comment by fogx** [comment]
basically this responsibility should not be on the NOW team imo. The NOW team should provide a stable and well-defined API, which the frontend team can use to easily implement search systems in vue, a popular JS framework.

**Comment by azayz** [comment]
Since this not team now responsibility I'll close this issue
