### ISSUE TITLE
fix: should pass user_input as env during flow deployment

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#633]
Currently, the user has to pass AWS credentials with each request to the remote flow. It accepts dict user_input as one of the params and then reads AWS cred from here. If the user_input is not passed in the param then the URI becomes inaccessible and the doc is not processed. We did not notice this before since the NOW app was essentially downloading the data first using the cred and then indexing it. Later, if somebody wanted to index more s3 docs then they must pass user_dict with AWS cred. This is unintuitive as the user would not know about the `UserInput` dataclass and also the bff is not clear.

When creating the flow, we should also send the user dict as env variable and store. This ticket aims to refactor by just accepting the cred in the request param to override the saved user_input.

**Comment by joschkabraun** [comment]
`UserInput` is set with the first request sent to the flow. After that it isn't required anymore, so I am not sure if that is an issue. But maybe I am missing something.

Did that issue appear with the sync job? I.e., did we not sent it there or is someone trying to index data after the empty flow is deployed without the sync job having started?

Additionally, I agree we shouldn't sent it with every index request but simply pass it to the custom gateway once and update if required. The custom gateway then enriches every request with that the API keys as it is the single source of truth. The preprocessor can become stateless again.
