### ISSUE TITLE
feat: enable real local deployment for testing

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#635]
Please enable deployment locally for apps. Instead of using a local kubernetes cluster, please make the deployment using the native jina orchestration. 

Currently this gives us technical limitations:
https://github.com/jina-ai/hubble/issues/723

UAC
- [ ] Jina orchestration for flow
- [ ] start BFF directly
- [ ] start playground directly

**Comment by nomagick** [comment]
I think you can simply replace `${JINA_NOW_COMMIT_SHA}` in `requirements.txt` to the git hash in CI using something like `sed`.
