### ISSUE TITLE
refactor: `ElasticIndexer` extends `BaseIndexer`

### ISSUE THREAD

**Issue by azayz** [jina-ai/now#638]
is there any reason why ElasticIndexer doesnt extend the BaseIndexer ? currently it's extending the AuthExecutor (BaseIndexer does this too) and QdrantIndexer extends the BaseIndexer, I would expect same behaviour for both indexers which is to extend the abstract base class BaseIndexer which is based on the AuthExecutor. 

UAC: 

- refactor Elastic Indexer to follow behaviour expected above

**Comment by maximilianwerk** [comment]
Does this still make sense, when we focus on ES for now?

**Comment by jupyterjazz** [comment]
`BaseIndexer` was removed so this can be closed
https://github.com/jina-ai/now/pull/890
