### ISSUE TITLE
bug: text-to-text app text splitting not working

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#643]
reported by @CatStark 

The whole text file becomes one giant search result.

Please split the input file into sentences. and index them separately.

![Image](https://user-images.githubusercontent.com/11627845/200633529-e5e3f1a6-c290-4022-92e2-35bbb9399c51.png)

**Comment by CatStark** [comment]
It's a docarray from a .txt

**Comment by violenil** [comment]
**Update**: split by sentence now happens on all datasets except the demo datasets (these are already split + encoded), so whether you are using docarray or any other dataset type (beside DEMO), all will be split by sentence. The only document that is not split by sentence is a query. We assume these to be short anyway.
