### ISSUE TITLE
bug: text-to-text does not work with local deployment

### ISSUE THREAD

**Issue by makram93** [jina-ai/now#657]
When trying to deploy the `text-to-text` app using any of the demo datasets, Jina Client is unable to connect to the gateway, i.e.
`c = Client(host='localhost', port=31080)` does not work and throws the following error.

![image](https://user-images.githubusercontent.com/6537525/201342821-b2144648-4b1d-4977-b7c9-637d1fed7b36.png)

All pods are in running state, yet the client can't connect
![image](https://user-images.githubusercontent.com/6537525/201342693-53c9fc78-2f74-4e19-8834-cd2cd371b9d4.png)

**Comment by violenil** [comment]
@makram93  can you verify that this is still true after recent refactoring/changes?

**Comment by makram93** [comment]
This one is working now. My local environment was causing problems. We can close this for now
