### ISSUE TITLE
feat: n to n support on elastic search cluster in production

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#671]
1. Currently, we host our elastic search cluster in a local deployment.
However, we need to provide a production-ready deployment for our customers.

The difficulty is that we need to bind the cluster creation to the flow.
Ideally, this would be happening within Wolf.
Whenever there is a flow deployed with the label: elastic, an elastic operator is deployed that can be used by the flow.

Hint
- pitching this to wolf
- if the pitch fails, find a solution made by us
- creating multiple tables on one cluster might be more cost-efficient.
UAC:
- [ ] each app deployment creates a table in the elastic search cluster
- [ ] when an app deployment is removed, the elastic search cluster or table is cleaned up as well

2. Default score calculation + custom score calculation on request level

UAC:
- [ ] default score calculation
- [ ] multi model queries
- [ ] multi model responses
- [ ] embeddings of the same embedding space are used for score calculation

Hint:
- document
- use new docarray representation made by core

**Comment by florian-hoenicke** [comment]
Just to make sure I have the right understanding of what you are saying.

You mean one could weight each of the score pairs individually?
Let's assume there is just one encoder.
You have two query fields and two output fields. In that case there are are 4 score pairs.

So option 1 is to have 4 weights for that
Option 2 is to have one weight.

You suggesting to go for option 2? I agree

**Comment by florian-hoenicke** [comment]
But yes I also think this would be great to investigate in the future.

**Comment by maximilianwerk** [comment]
- [ ] finish indexing (Isabelle)
- [ ] enable searching with bm25_text field (Max)
- [ ] dynamic bm25 fields from document tags
- [ ] enable elastic cloud usage (Max)
- [ ] refactor list to use ES offset and limit

Next iteration
- [ ] refactor ES query building to own class for better testing and explicit interface building
- [ ] field boosting via bm25
