### ISSUE TITLE
bug: text-to-video deployment broken (uri-bucket)

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#704]
As you can see, the assignment of the modality is made after the file is downloaded. Therefore the file-ending is deleted.
Please determine the modality before downloading the file based on the file ending.

![Image](https://user-images.githubusercontent.com/11627845/203998756-b6f8f210-91f2-4d3c-bd6c-33757b703765.png)

**Comment by makram93** [comment]
@florian-hoenicke 
I deployed the video app with s3 as the data source and found that the URI was preserved at the pre-processor when debugging it locally. 

![image](https://user-images.githubusercontent.com/6537525/204298065-f9cd13c6-ad09-456d-9e77-8b524f9b6360.png)

Can you let me know what data source did you use?
