### ISSUE TITLE
bug: playground text should be first modality

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#723]
Please correct the order of the input

UAC
- [x] order: text, upload, webcam  - or - you can make it dependent on the order of text-or-image 

![Image](https://user-images.githubusercontent.com/11627845/205017340-b6fc5968-b3d0-4451-875f-0c8e873d4972.png)

**Comment by IyadhKhalfallah** [comment]
[

![Image](https://user-images.githubusercontent.com/35614094/208065001-43bd44be-46b9-48fa-94c7-e990ae3b8002.png)

](url)
