### ISSUE TITLE
bug: replicas not working for local deployment

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#745]
For local deployment, it does not work to have more than 1 replica for an executor.
This is because the logic of performing the waiting is not correct. It assumes the number of pods == number of deployments.
Please wait for the the number of executors * replicas to become ready.

**Comment by joschkabraun** [comment]
Easiest solution is to skip waiting after to k8s conversion, and only rely on checking readiness by sending documents to the flow.

Additionally, replace current logic with https://docs.jina.ai/concepts/flow/readiness/.
