### ISSUE TITLE
bug: video app is not selected when indexing gif files

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#779]
As you can see. the text retrieval app is selected when indexing gif files.

Solution:
Remove the video app and handle video within the search app

Specified folder with the gif files:
![Image](https://user-images.githubusercontent.com/11627845/208676087-b3f1c3ab-de73-4837-947f-1bf3e15be944.png)

Selected gif as search field:
![Image](https://user-images.githubusercontent.com/11627845/208676005-fe1616e1-ba9b-456f-bd38-46722f3e2de5.png)

Within the code execution, it selects our text/image app instead of video. Therefore the high performance flow is not running
![Image](https://user-images.githubusercontent.com/11627845/208675533-2d111934-63c2-495e-89c3-d46cdaaa5a8e.png)

**Comment by joschkabraun** [comment]
Has been fixed by #788.
