### ISSUE TITLE
bug: customer deployment doesn't work

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/now#780]
There are no filters visible and no search results returned
<img width="1430" alt="Screenshot 2022-12-20 at 14 38 41" src="https://user-images.githubusercontent.com/45267439/208680311-13066eb1-3009-42d1-8d3e-7d3dff9c59b1.png">

As Florian mentioned, flow is still running, so the issue should be on the application side

relevant discussion 
https://jinaai.slack.com/archives/C01E03LN3K7/p1671543477473789

**Comment by joschkabraun** [comment]
it works in newer PRs
