### ISSUE TITLE
bug: local playground doesn't work

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/now#792]
<img width="735" alt="Screenshot 2022-12-21 at 15 41 49" src="https://user-images.githubusercontent.com/45267439/208931397-5438e860-974d-452c-8ea7-dbadfe54c699.png">

Steps to reproduce:

1. run playground locally
2. create a remote app
3. access the app from local playground

**Comment by joschkabraun** [comment]
What's the URL you used?

**Comment by jupyterjazz** [comment]
@joschkabraun sent you on slack

**Comment by joschkabraun** [comment]
Okay, the URL works for me

**Comment by jupyterjazz** [comment]
Domain needed to be changed, thanks for helping
