### ISSUE TITLE
fix: playground support for output modality

### ISSUE THREAD

**Issue by IyadhKhalfallah** [jina-ai/now#821]
In the playground, output_modality for previous types is still supported. The cloud team reported this bug happening, and this is due to what's mentioned

![Image](https://user-images.githubusercontent.com/35614094/209659262-caca4a5e-3eda-41ca-ba4c-dce3f5a9a80e.png)

**Comment by joschkabraun** [comment]
I think we can remove `output_modality` entirely from the playground code basis, as it will always be `text-or-image-or-video`.
