### ISSUE TITLE
docs: update API documentation

### ISSUE THREAD

**Issue by violenil** [jina-ai/now#837]
The documentation of our API needs to be updated. For example, the request body of a search should look something like this:

```
{
  "host": "grpcs://smart-404-nowapi-69dd3b9487.wolf.jina.ai",
  "port": "443",
  "query": {"text_field": {"text": "red shoes"}},
  "limit": "3"   
}
```

**Comment by makram93** [comment]
https://jinaai.slack.com/archives/C01E03LN3K7/p1674215927015489
