### ISSUE TITLE
fix: wrong indexing of docarrays

### ISSUE THREAD

**Issue by IyadhKhalfallah** [jina-ai/now#854]
docarray indexing is not taking into consideration index_fields, it is also failing with the new support of elastic_indexer

- [x] https://github.com/jina-ai/now/issues/908
- [ ] https://github.com/jina-ai/now/issues/910

**Comment by xumx** [comment]
Can we get this fixed soon? It makes the current version of Now cloud completely unusable. Even for very basic text search.

**Comment by IyadhKhalfallah** [comment]
@xumx This is currently being reviewed, it should be merged soon.
