### ISSUE TITLE
performance: improve listing files from s3

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#927]
Ticket created by Chat GPT:

# question
I get all files from an s3 bucket.
```python
bucket.objects.filter(Prefix=folder_prefix)
```
The problem is that it is slow. How can I make this run much faster?

# Answer
There are a few ways you could try to make this run faster:

Using the boto3 paginator to retrieve the objects in batches. This can help reduce the number of API calls made to retrieve the objects, and can improve performance. For example:

```python
    s3 = boto3.client('s3')
    paginator = s3.get_paginator('list_objects_v2')
    pages = paginator.paginate(Bucket=bucket_name, Prefix=folder_prefix)
    for page in pages:
        for item in page['Contents']:
            # Do something with the item
```

Set up a multithreading or multiprocessing, you can use the concurrent.futures library in Python to create a pool of worker threads or processes to handle the API calls in parallel.

Caching in an EC2 instance or Lambda function that runs on the same VPC as the S3 bucket. This can help reduce network latency and improve performance

If your concern is on getting very large data, one thing you can try is to do is to only retrieve the information you need, instead of retrieving all of the objects and then filtering through them. If you know which objects you are looking for, you can use the get_object method to retrieve just those objects.

Look into the AWS Glue Crawler, which creates a table and partitions on s3 data. Then use AWS Athena or Glue Job to query the data and retrieve only the information you need.

Using the S3 Select feature, which allows you to filter the data in an S3 object before you retrieve it. This can reduce the amount of data you need to retrieve and process, which can improve performance.

It is worth noting that the most appropriate solution will depend on the specific use case and the size and complexity of the data you are working with.

It could be useful to run a test with different approach to see which one gives you the best performance results, and use that as your solution.

```

**Comment by IyadhKhalfallah** [comment]
The suggested performance does not drastically improve the performance of listing s3 files. What would be efficient, according to [this blogpost](https://blog.purestorage.com/purely-technical/listing-67-billion-objects-in-1-bucket/) is to ensure concurrent calls to list the elements (by creating an event loop and a threadpool). The blocker we currently have is that the prompt is already using the event loop, which creates a deadlock to the resource. I will close this ticket, as it is done, and move to a less priority ticket to investigate the solution described above.
