### ISSUE TITLE
bug: flattened tags are not read

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/now#945]
We flatten filters that are given as a nested structure
<img width="357" alt="Screenshot 2023-01-17 at 15 13 01" src="https://user-images.githubusercontent.com/45267439/212921295-2e241a84-3176-4e32-9172-7c784c2583bb.png">
That's how they're stored in a dataclass

However, when we actually create docs, we don't flatten but match directly to (in this case) `tags`
https://github.com/jina-ai/now/blob/011a5bcb32c066eab179d673de2d490807167b39/now/data_loading/data_loading.py#L237
Thus, flattened filters are disregarded

**Comment by violenil** [comment]
#949
