### ISSUE TITLE
docs: visualize jina search

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#970]
Illustrate and describe how the following components interact with each other and how JCloud should be mimicking the website search app.
- [x] now package
- [x] deployed flows
- [x] Jina Cloud Apps website
- [x] Jina Cloud API
- [x] Jcloud package

Search Flow:

![Image](https://user-images.githubusercontent.com/11627845/214355629-c8759771-71aa-4629-93e6-f49941aad536.png)

**Comment by fogx** [comment]
related discussions:
[1](https://jinaai.slack.com/archives/C01E03LN3K7/p1673943060266719)
[2](https://jinaai.slack.com/archives/C01E03LN3K7/p1674549853641539)

[previous visualization](https://www.figma.com/file/okM8rW7d3W9WsTLCCO3csI/Jina-NOW-Diagrams?node-id=0%3A1&t=oNza6RSGEn7ntbpw-0)

**Comment by florian-hoenicke** [comment]
Graphic - work in progress

**Comment by florian-hoenicke** [comment]
@fogx what do you think about this. Is it sufficient?

**Comment by joschkabraun** [comment]
@CatStark is that sufficient as technical document we need for the client?

**Comment by fogx** [comment]
@florian-hoenicke some questions that came up since yesterday:

- is the Cloud Apps API used for creation as well as querying or are these separate?
- Where is the payment logic located? In the custom gateway?
- is there other logic in the custom gateway?

**Comment by CatStark** [comment]
@joschkabraun This is something we can base our document for them if we continue, but not something we send them as it is right?

**Comment by florian-hoenicke** [comment]
@fogx thanks for the feedback. I will include the questions

**Comment by florian-hoenicke** [comment]
Hi @fogx, I adjusted the graphic. 
- search requests don't hit our now-api
- billing logic is in the bff
