### ISSUE TITLE
Bug: Deleting an App does not remove the Flow

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/now#973]
Bug:
When I remove a Search App in the frontend, I can still see the Flow with `jcloud list`. Most probably it is still alive.

Expected behavior:
I expect a Flow to be removed, when I remove the Search App.

![image](https://user-images.githubusercontent.com/4920275/214307590-d1bb787a-3f43-4a7c-8872-3bd5b385c509.png)

**Comment by azayz** [comment]
https://github.com/jina-ai/now.private/pull/273
