### ISSUE TITLE
refactor: remove filter fields from dataclass creation

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/now#974]
Filter fields shouldn't be a field in the dataclass we create but only the index fields. The filter fields should only appear as tags.

Hint:
- one relevant location in code of `create_dataclass_fields_file_mappings`: https://github.com/jina-ai/now/blob/main/now/data_loading/create_dataclass.py#L164

**Comment by jupyterjazz** [comment]
I think Iyadh's already working on it?
https://github.com/jina-ai/now/issues/949

**Comment by jupyterjazz** [comment]
I took over on this since https://github.com/jina-ai/now/issues/971 is related to this ticket
