### ISSUE TITLE
feat: add video stream

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#98]

**Comment by makram93** [comment]
Seems like streamlit does not have official support for the [video stream](https://discuss.streamlit.io/t/live-webcam-feed-into-the-web-app/397/4#:~:text=Sorry,shared%20app%20mode.): 

However, there are public repos which provides support for the video streaming in streamlit app. There is a caveat - these [libraries](https://github.com/tconkling/streamlit-webcam) only support video streams for the app run locally. 
TODO:
- [ ] Investigate available libraries
- [ ] Implement the solution using any one of the approaches
- [ ] Test - local and cloud deployment
