### ISSUE TITLE
performance: create concurrent calls for listing s3 buckets

### ISSUE THREAD

**Issue by IyadhKhalfallah** [jina-ai/now#983]
This ticket is destined to improve the listing using concurrent calls, according to [this article](https://blog.purestorage.com/purely-technical/listing-67-billion-objects-in-1-bucket/). 
It is also important to note that this ticket solves the problem of having an event loop inside the prompt one already existing.

Ideas:
- using aws cli library
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory.html
- https://alukach.com/posts/tips-for-working-with-a-large-number-of-files-in-s3/

**Comment by IyadhKhalfallah** [comment]
boto3 resources [are not thread safe](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html?highlight=multithreading#multithreading-multiprocessing)

**Comment by IyadhKhalfallah** [comment]
@florian-hoenicke 
- using aws cli is not better than the solution implemented in the PR because there is no way to use a delimiter and parallelise calls in the CLI. Thus, we can only use a straightforward aws --profile [PROFILE] s3 ls [S3_FOLDER] --recursive >> text.txt which will take the same time as the list_objects.
- The s3 inventory needs a lot of access: Asking the client to create an inventory and giving access to the boto3 "client" (since now we only have access to "resource").

**Comment by florian-hoenicke** [comment]
Does it help if we create a bucket on our own and then synch it with their bucket? Or is that even slower?

**Comment by IyadhKhalfallah** [comment]
@florian-hoenicke It would take the same time to transfer the data. Even though we might investigate solutions (Like AWS DataSync) but I think we still need permissions so, the request is still the same as above (asking for more permissions). What do you think?
