### ISSUE TITLE
bug: reaching quota on flow deployments

### ISSUE THREAD

**Issue by violenil** [jina-ai/now#994]
We are often seeing tests in CI fail because we reached the quota for flow deployments. See [here](https://github.com/jina-ai/now/actions/runs/4042939753/jobs/6952796236#step:6:126).
With `jc list` you can then see we have tons of flows deployed that are not being removed:

![Image](https://user-images.githubusercontent.com/55404563/215502105-2eabbeb3-e3ab-466a-934d-1dada5eb0b53.png)

Investigate where these flows are coming from (probably CI tests) and why they are not being removed.

**Comment by joschkabraun** [comment]
This was because flows weren't removed in custom gateway PR (https://github.com/jina-ai/now/pull/921) for the longest time as the `host` had changed to `http`.
